dataset:
  n_names: 10
  save_dir: "data"

training:
  model: "gpt-4.1-nano-2025-04-14"
  training_file: "data/train.jsonl"
  epochs: auto
  learning_rate: auto
  batch_size: auto
  suffix: "country-capital"

test:
  test_file: "data/test.jsonl"
