dataset:
  n_names: 100
  save_dir: "data"
  
training:
  model: "gpt-4.1-nano-2025-04-14"
  # model: "gpt-4.1-mini-2025-04-14"
  # model: "gpt-4.1-2025-04-14"
  training_file: "data/train.jsonl"
  epochs: 30
  learning_rate: auto
  batch_size: auto
  suffix: "country-capital"
  resume_job_id: 

test:
  test_file: "data/test.jsonl"
  results_dir: -1  # -1 = latest, or use specific integer. test.py pulls the model_id from here.
  max_concurrent: 20

plotting:
  results_dir: -1 
